<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/13.0.0">
  <PropertyGroup>
    <Version>0.1.4-api13-tw</Version>
    <AssemblyName>AutoPincher</AssemblyName>
    <RootNamespace>AutoPincher</RootNamespace>
    <PackageProjectUrl>https://github.com/XivHub/AutoPincher</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <DalamudLibPath>$(HOME)/Library/Application Support/XIV on Mac in TC/dalamud/Hooks/dev/</DalamudLibPath>
    <AssemblySearchPaths>$(AssemblySearchPaths);$(DalamudLibPath)</AssemblySearchPaths>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ECommons" Version="3.0.1.3" />
  </ItemGroup>
</Project>
